# shared_labels.py
FRIENDLY_LABELS = {
    "music-library": "Music Library",
    "library": "Music Library",
    "artists": "Artists",
    "albums": "Albums",
    "genres": "Genres",
    "webradio": "Web Radio",
    "radio": "Web Radio",
    "radio_paradise": "Radio Paradise",
    "tidal": "Tidal",
    "qobuz": "Qobuz",
    "internal": "Internal",
    "config": "Config",
    "nas": "NAS",
    "usb": "USB",
    "playlists": "Playlists",
    "spotify": "Spotify",
    "spop": "Spotify",
    "motherearth": "Mother Earth",
    "favourites": "Favourites",
    "favorites": "Favourites",
    "last_100": "Last 100",
    "mediaservers": "Media Servers",
    "upnp": "UPnP",
}
